### IMPORTING NECESSARY LIBRARIES

In [1]:
import tweepy
import pandas as pd
import re

### USING THE API TO EXTRACT TWEETS

In [2]:
consumer_key = "XXXXXXXXXXXXXXXX"
consumer_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

In [3]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

### EXTRACTING THE TWEETS

In [4]:
number_of_tweets = 5000
tweets = []
likes = []
time = []
tweet_id = []
retweets = []

for i in tweepy.Cursor(api.search_tweets, q='Covid-19', tweet_mode='extended', lang = 'en').items(5000):
    tweets.append(i.full_text)
    likes.append(i.favorite_count)
    time.append(i.created_at)
    tweet_id.append(i.id)
    retweets.append(i.retweet_count)

### CREATING A DATAFRAME FOR THE TWEETS

In [11]:
df = pd.DataFrame({'tweets':tweets, 'likes':likes, 'time':time, 'retweets':retweets,})
df

,tweets,likes,time,retweets
0,RT @akbarth3great: GOP leaders escalate battle...,0,2021-10-23 17:14:42+00:00,2
1,RT @RashidaTlaib: I lost a childhood friend to...,0,2021-10-23 17:14:41+00:00,193
2,"RT @schellhornmusic: The death of music? ""69,0...",0,2021-10-23 17:14:41+00:00,18
3,@Caramel_Angel7 About as much as we’re gonna m...,0,2021-10-23 17:14:41+00:00,0
4,"RT @VP: Our nurses, doctors, technicians, and ...",0,2021-10-23 17:14:40+00:00,1461
5,"RT @embalamrselvam: Issued cheque of Rs. 50,00...",0,2021-10-23 17:14:40+00:00,37
6,RT @circleofmamas: Submit your public comment ...,0,2021-10-23 17:14:39+00:00,1
7,RT @jsolomonReports: Whitmer fallout: Audit fi...,0,2021-10-23 17:14:39+00:00,1196
8,RT @DrLeeJones: Microbiologist Professor David...,0,2021-10-23 17:14:39+00:00,210
9,Republican politicians escalate battle against...,0,2021-10-23 17:14:39+00:00,0

In [ ]:
df.to_csv('covid.data.csv')

In [17]:
data.head()

,Unnamed: 0,tweets,likes,time,retweets
0,0,RT @annmarietimmins: DHHS has asked me to make...,0,2021-10-22 21:43:06+00:00,3
1,1,RT @GandBLawyers: Singapore with one of the hi...,0,2021-10-22 21:43:06+00:00,56
2,2,RT @Crof: Saskatoon hospital so full of COVID-...,0,2021-10-22 21:43:06+00:00,3
3,3,RT @mandophotos: A Day of the Dead ofrenda cre...,0,2021-10-22 21:43:04+00:00,952
4,4,RT @praveenausa: @hazydav @RepMattGaetz … ...,0,2021-10-22 21:43:03+00:00,1

In [18]:
data.sample(10)

,Unnamed: 0,tweets,likes,time,retweets
1854,1854,RT @ibusolih: Congratulations to PM @narendram...,0,2021-10-22 21:28:02+00:00,1842
1051,1051,RT @RasuShrestha: Following approvals by the F...,0,2021-10-22 21:33:54+00:00,1
1936,1936,@_____Wimpy @MarshaBlackburn Statistic is misa...,0,2021-10-22 21:27:18+00:00,0
1787,1787,RT @MaidmentRos: We keep hearing about rising ...,0,2021-10-22 21:28:31+00:00,240
1570,1570,"According to Father Christopher Colavito, the ...",0,2021-10-22 21:30:03+00:00,0
1751,1751,"RT @LloydHardy: 100K cases a day is coming, we...",0,2021-10-22 21:28:46+00:00,499
714,714,RT @RNAO: RNAO's report on its Work and Wellbe...,0,2021-10-22 21:36:56+00:00,8
1477,1477,Can’t wait to be able to send our kids to scho...,1,2021-10-22 21:30:31+00:00,0
1680,1680,RT @JossWaddyProEU: @lucyallan If the NHS let ...,0,2021-10-22 21:29:17+00:00,2
993,993,RT @EmeraldRobinson: Dr. Fauci is not just mor...,0,2021-10-22 21:34:32+00:00,3546